/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoBriketErpRouteImport } from './routes/demo/briket-erp'
import { Route as DemoBriketMiniAppRouteImport } from './routes/demo/briket-mini-app'
import { Route as DemoKonkursBotRouteImport } from './routes/demo/konkurs-bot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBriketErpRoute = DemoBriketErpRouteImport.update({
  id: '/demo/briket-erp',
  path: '/demo/briket-erp',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBriketMiniAppRoute = DemoBriketMiniAppRouteImport.update({
  id: '/demo/briket-mini-app',
  path: '/demo/briket-mini-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKonkursBotRoute = DemoKonkursBotRouteImport.update({
  id: '/demo/konkurs-bot',
  path: '/demo/konkurs-bot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/briket-erp': typeof DemoBriketErpRoute
  '/demo/briket-mini-app': typeof DemoBriketMiniAppRoute
  '/demo/konkurs-bot': typeof DemoKonkursBotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/briket-erp': typeof DemoBriketErpRoute
  '/demo/briket-mini-app': typeof DemoBriketMiniAppRoute
  '/demo/konkurs-bot': typeof DemoKonkursBotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/briket-erp': typeof DemoBriketErpRoute
  '/demo/briket-mini-app': typeof DemoBriketMiniAppRoute
  '/demo/konkurs-bot': typeof DemoKonkursBotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/demo/briket-erp' | '/demo/briket-mini-app' | '/demo/konkurs-bot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/briket-erp' | '/demo/briket-mini-app' | '/demo/konkurs-bot'
  id:
    | '__root__'
    | '/'
    | '/demo/briket-erp'
    | '/demo/briket-mini-app'
    | '/demo/konkurs-bot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBriketErpRoute: typeof DemoBriketErpRoute
  DemoBriketMiniAppRoute: typeof DemoBriketMiniAppRoute
  DemoKonkursBotRoute: typeof DemoKonkursBotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/briket-erp': {
      id: '/demo/briket-erp'
      path: '/demo/briket-erp'
      fullPath: '/demo/briket-erp'
      preLoaderRoute: typeof DemoBriketErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/briket-mini-app': {
      id: '/demo/briket-mini-app'
      path: '/demo/briket-mini-app'
      fullPath: '/demo/briket-mini-app'
      preLoaderRoute: typeof DemoBriketMiniAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/konkurs-bot': {
      id: '/demo/konkurs-bot'
      path: '/demo/konkurs-bot'
      fullPath: '/demo/konkurs-bot'
      preLoaderRoute: typeof DemoKonkursBotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBriketErpRoute: DemoBriketErpRoute,
  DemoBriketMiniAppRoute: DemoBriketMiniAppRoute,
  DemoKonkursBotRoute: DemoKonkursBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
